version: '3'
services:
    nginx:
        image: nginx
        ports:
            - '8888:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        container_name: 'nginx'
        restart: unless-stopped
        networks:
            my-network:
                ipv4_address: 192.168.0.5
    redis:
        image: redis
        ports:
            - '6379:6379'
        container_name: 'redis'
        networks:
            my-network:
                ipv4_address: 192.168.0.2
    master-node-1:
        image: 'mgimenezdev/p2p-master-redis:latest'
        ports:
            - '8081:8080'
        container_name: 'master-node-1'
        networks:
            my-network:
                ipv4_address: 192.168.0.100
    master-node-2:
        image: 'mgimenezdev/p2p-master-redis:latest'
        ports:
            - '8082:8080'
        container_name: 'master-node-2'
        networks:
            my-network:
                ipv4_address: 192.168.0.101
    end-node-1:
        image: 'mgimenezdev/p2p-end:latest'
        ports:
            - '9000:9000'
        container_name: 'end-node-1'
        environment:
            IP_ADDRESS: 192.168.0.150
            PORT: 9000
        networks:
            my-network:
                ipv4_address: 192.168.0.150
    end-node-2:
        image: 'mgimenezdev/p2p-end:latest'
        ports:
            - '9001:9000'
        container_name: 'end-node-2'
        environment:
            IP_ADDRESS: 192.168.0.151
            PORT: 9001
        networks:
            my-network:
                ipv4_address: 192.168.0.151
    end-node-3:
        image: 'mgimenezdev/p2p-end:latest'
        ports:
            - '9002:9000'
        container_name: 'end-node-3'
        environment:
            IP_ADDRESS: 192.168.0.152
            PORT: 9002
        networks:
            my-network:
                ipv4_address: 192.168.0.152
    end-node-4:
        image: 'mgimenezdev/p2p-end:latest'
        ports:
            - '9003:9000'
        container_name: 'end-node-4'
        environment:
            IP_ADDRESS: 192.168.0.153
            PORT: 9003
        networks:
            my-network:
                ipv4_address: 192.168.0.153
networks:
    my-network:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.0.0/24
