name: Pipeline P2PNetworkSpringboot

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Build EndNode with Maven
              working-directory: ./EndNode
              run: mvn clean package
            - name: Build MasterNode with Maven
              working-directory: ./MasterNode
              run: mvn clean package

            - name: Build Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: false
                  file: ./Dockerfile
                  tags: your-dockerhub-username/your-image-name:latest
