version: '3'
services:
    nginx:
        image: nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
# Luego, deberia levantar dos contenedores de nodos maestros y algunos nodos extremos
