version: '3'
services:
    
    master-node-1:
        image: 'dileydl/master-node:latest'
        ports:
            - '8080:8080'
        container_name: 'master-node-1'
        network_mode: "host"
    end-node-1:
        image: 'dileydl/end-node:latest'
        ports:
            - '9000:9000'
        container_name: 'end-node-1'
        environment:
            IP_ADDRESS: 192.168.0.150
            PORT: 9000
        network_mode: "host"
    end-node-2:
        image: 'dileydl/end-node:latest'
        ports:
            - '9001:9000'
        container_name: 'end-node-2'
        environment:
            IP_ADDRESS: 192.168.0.151
            PORT: 9001
        network_mode: "host"
