version: '3'
services:
    
    master-node-1:
        image: 'dileydl/master-node:latest'
        ports:
            - '8080:8080'
        container_name: 'master-node-1'
        networks:
            my-network:
                ipv4_address: 192.168.0.100
    end-node-1:
        image: 'dileydl/end-node:latest'
        ports:
            - '9000:9000'
        container_name: 'end-node-1'
        environment:
            IP_ADDRESS: 192.168.0.150
            PORT: 9000
        networks:
            my-network:
                ipv4_address: 192.168.0.150
    end-node-2:
        image: 'dileydl/end-node:latest'
        ports:
            - '9001:9000'
        container_name: 'end-node-2'
        environment:
            IP_ADDRESS: 192.168.0.151
            PORT: 9001
        networks:
            my-network:
                ipv4_address: 192.168.0.151
networks:
    my-network:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.0.0/24
