name: P2PNetworkRedis workflow

on:
    push:
        branches:
            - main
        paths:
            - 'practica2/2-Sobel/DistributedSobel/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: 17

            - name: Build SplitService with Maven
              working-directory: ./practica2/2-Sobel/DistributedSobel/SplitService
              run: mvn clean package

            - name: Build MessageQueue with Maven
              working-directory: ./practica2/2-Sobel/DistributedSobel/MessageQueue
              run: mvn clean package

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push SplitService Docker image
              uses: docker/build-push-action@v2
              with:
                  context: ./practica2/2-Sobel/DistributedSobel/SplitService
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/image-split-service:latest

            - name: Build and push MessageQueue Docker image
              uses: docker/build-push-action@v2
              with:
                  context: ./practica2/2-Sobel/DistributedSobel/MessageQueue
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/tasks-queue-service:latest
